module.exports = {
  üyeBelirt: `${emojiler.hata} **UYARI:** Lütfen geçerli bir üye etiketleyin ya da ID belirtiniz.`,
  üyeYok: `${emojiler.hata} **UYARI:** Lütfen geçerli bir üye etiketleyin ya da ID belirtiniz.`,
  üyeBot: `${emojiler.hata} **UYARI:** Sunucudaki bir bot üzerinde işlem yapamazsınız.`,
  üyeKayıtsız: `${emojiler.hata} **UYARI:** Bu üye sunucuda zaten kayıtlı değil.`,
  üyeKayıtlı: `${emojiler.hata} **UYARI:** Bu üye sunucuda zaten kayıtlı bulunuyor.`,
  isimBelirt: `${emojiler.hata} **UYARI:** Lütfen geçerli bir isim belirtiniz.`,
  yaşBelirt: `${emojiler.hata} **UYARI:** Lütfen geçerli bir yaş belirtiniz.`,
  tagsızÜye: `${emojiler.hata} **UYARI:** Bu kullanıcı tagımızı bulundurmadığı için işlem gerçekleştirilemiyor.`,
  isimApiSınır: `${emojiler.hata} **UYARI:** Kullanıcı isim uzunluğu en fazla 32 karakter olabilir.`,
  botSahibi: `${emojiler.hata} **UYARI:** Bu kullanıcı üstünde işlem yapamam.`,
  kendisi: `${emojiler.hata} **UYARI:** Kendi üzerinizde bir işlem yapamazsınız.`,
  sebepBelirt: `${emojiler.hata} **UYARI:** Lütfen geçerli bir sebep belirtiniz.`,
  süreBelirt: `${emojiler.hata} **UYARI:** Lütfen bir süre belirtiniz. \`(1m = 1 dakika / 1h = 1 saat / 1d = 1 gün / 1w = 1 hafta)\``,
  yetersizYetkim: `${emojiler.hata} **UYARI:** Bu kullanıcı üzerinde işlem yapmak için herhangi bir yetkiye sahip değilim.`,
  üstAynıYetki: `${emojiler.hata} **UYARI:** Bu kullanıcı sizden üst/aynı yetiye sahip.`,
  banlı: `${emojiler.hata} **UYARI:** Bu kullanıcı sunucumuzda zaten yasaklı.`,
  banlıDeğil: `${emojiler.hata} **UYARI:** Bu kullanıcı sunucumuzda yasaklı değil.`,
  cezalı: `${emojiler.hata} **UYARI:** Bu kullanıcı cezalıda bulunduğu için işlem yapılamaz.`,
  cezalıDeğil: `${emojiler.hata} **UYARI:** Bu kullanıcı cezalıda bulunmuyor.`,
  muteli: `${emojiler.hata} **UYARI:** Bu kullanıcı metin kanallarında zaten susturulmuş`,
  muteliDeğil: `${emojiler.hata} **UYARI:** Bu kullanıcı metin kanallarında zaten susturulmamış`,
  yeniHesap: `${emojiler.hata} **UYARI:** Bu kullanıcı yeni hesap olduğu için işlem yapılamaz.`,
  yasaklıTag: `${emojiler.hata} **UYARI:** Bu kullanıcı yasaklı tagda bulunduğu için işlem yapılamaz.`,
  sunucuSahibi: `${emojiler.hata} **UYARI:** Sunucu sahibi üzerinde işlem yapamazsın.`,
  rolBelirt: `${emojiler.hata} **UYARI:** Lütfen geçerli bir rol belirtiniz.`,
}